travis:
  secure:
    BINSTAR_TOKEN: M4UPUvxQtih/4lh0rQHxBhEMn1PwFC41UjLRAxoG87sJDqIkSbqmIF9ffyiZ5QqSFI4wtvS6ut0V+7Veko+f0N4f47Wf+2L9FDUcavqRORp3/N8K+LZgjzHFVCYcnkQNGFVIP0E9SVpUHW0AUcSQHstUbowK39P4qLbxVA5shtlT3D/alrTh2sGdi/bSIYwBpQY7AkLfc5BhhJvH0/4xgVr2M1mHBisM4vikcljsH9hREy9Q0sg0i2nnSFvE+CvYnQbweJkf1psLsijncG2g9+BC9/l/mMJUIDxqXykck6uTfmrhEFo3BxpO+f/k1BcKUGRoovZCRXoRYKiEn74lFjxrg9wBK+XP7limlpnKGn7VzMJKclvhq4Rlz8e6FNTJyzg++7UMIMIY5CKdtuzvqvwMh1Av77Dfr+rGlvO4iXiy+L29pIhlnsxuo9BP0/cJFCvE6dSdfwTrc2Q4veVSATCDv2PYq7M5Kq5iDiWB21SH60PQS7YURZx9JMmeibeVyKrbOov/mW4t284x+I3SPWqIg2nQvryGDF5JQL0Kq4jVypLaR64UBi8TMOJrilNWsi7HiqwJWXEaPjw6DDw+0lR6xvI+oGmvk4KUfz3nhcS7q4V/6UpV8fWJBBipW5wS+jpgXvjP2DwxmmDRYQYykkEzb6Ug1qgIKHV/GnQgnxg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
