travis:
  secure:
    BINSTAR_TOKEN: O1cglI5lRCW/WNwF4fYNYUaXfvMnBWKxMHoDyd5xg8NEhy3uxVXWM2ifxLc8ajffdoeZsgSnttSXnBoXLbOiphFyi35KJGfx/9Wgw6JNxd8drNsAJeeTYn9ctsgzDSi2cLpU2xF+IohMHyEWm8W2f4t5gJjRhGYZo80+duHiYlr1XHX36UWEUj91J2yJ4Jn5tus83UCtPeE0G6yE4bjgQf3eD2nk2SokghIPjGn9UUKF9aaSE1Wwk4Lt4fP8tB0ZmWKt9zugLaLvfJgZduBBI470lsAoV9BSsFRA3V2sXH9VNHaAMwQhcLgzxG99L96RqihdpT+cGNFUJH3ZbbNrhOKpUeGKBgHWWgRDnuebmNbzAWmm5ZHa5PkxW0Jxxw4k08yzMmfW+w1bsE4+ESoCoyoK0kXn0Z45iKNga+z9+M/hrbR3uWyq6I9xGnrNLtw8Ya4nN9eWT3iZsAk/yW48AWpVVIhRrYOQ+KkBXC+T9tkxcMccykmPmmrZVbSJJjnUbPtwqD1UGFBUMqqutKVjwcmhg7uJHZZAkiM72BVx4fF/3GN/1YASg6XG6xY2EfYq4u6q0jUP7KiLRN7soS5OrZUABIAEPNJ2MijwQZ+Bq8AYtRk7CVOl2RPvQ6zLmT8/EdFTJQ84ZZC2yysV9YNdp03XFWDhFaoD5qNERx2CMzM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
